Add tagging functionality to Jenkinsfile
IYermakov/Snakes pull request #22
Opened 2019-11-28 15:39 UTC by velychkovskyi

2019-11-28 15:54 UTC, vecinomio approved these changes
Looks Good To Me

2019-12-03 12:42 UTC, mike-unitskyi requested changes

2019-12-03 12:42 UTC, mike-unitskyi commented on Jenkinsfile
>      booleanParam(name: 'Test', defaultValue: true, description: '')
wouldn't extract this as separate parameter (should be the same as `build`)

2019-12-03 12:42 UTC, mike-unitskyi commented on Jenkinsfile
>      booleanParam(name: 'Tagging', defaultValue: false, description: '')
would combine `Tagging` and `Delivery` to `release`.

2019-12-03 12:42 UTC, mike-unitskyi commented on Jenkinsfile
>      booleanParam(name: 'BuildApp', defaultValue: true, description: '')
would rename to `build`

2019-12-05 09:13 UTC, closed without merging